trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: 'UserDetailsExtraction.ps1'
      arguments: ''
      errorActionPreference: 'stop'